In [28]:
#A function so that the columns of the output matrix are powers of the input vector. 
#The order of the powers is determined by the increasing boolean argument. 
#Specifically,when increasing is False,the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#Import the numpy package
import numpy as np

#User defined function 'myfunc' which takes parameters as:
#arr: The input vector
#increasing: The boolean parameter to determine the order of the powers. Default is 'False'

def myfunc(arr, increasing=False):
    
    #Get the size of input array 
    size = len(arr)
    
    #Check if the value of increasing is True or False
    if increasing == True:
        #Return the matrix in order of increasing powers
        return np.fromfunction(lambda j, i: arr[j]**i, (size, size), dtype=int)
    else:
        #Return the matrix in order of decreasing powers
        return np.fromfunction(lambda j, i: arr[j]**(size-i-1), (size, size), dtype=int)

#Usage of myfunc function
arr1 = np.array([1,5,6])
mat1 = myfunc(arr1)
print("The input vector1 is: ", arr1)
print("The output matrix1 is (increasing = False by default):\n", mat1)

arr2 = np.array([3,4,5,7])
mat2 = myfunc(arr2, True)
print("The input vector2 is: ", arr2)
print("The output matrix2 is (increasing = True):\n", mat2)

The input vector1 is:  [1 5 6]
The output matrix1 is (increasing = False by default):
 [[ 1  1  1]
 [25  5  1]
 [36  6  1]]
The input vector2 is:  [3 4 5 7]
The output matrix2 is (increasing = True):
 [[  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   7  49 343]]
